module.exports = {
  title: 'gift',
  author: 'アンモナイト <ammonitedx@gmail.com>',
  language: 'ja',
  size: 'A5',
  theme: 'themes/vivliostyle-theme-dx3rd-ammonite',
  entry: [
    'toc.html',
    'preplay.html',
    'npcs.html',
    'scenes.html',
    'op1.html',
    'op2.html',
    'op3.html',
    'md1.html',
    'md2.html',
    'md3.html',
    'md4.html',
    'md5a.html',
    'md5b.html',
    'md6a.html',
    'md6b.html',
    'md7.html',
    'cl1.html',
    'ed1.html',
    'afterplay.html',
    'liszt.html',
    'shiro.html',
    'kuro.html',
    'appendix.html'
  ],
  entryContext: 'manuscripts',
}
